import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Card from "./Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.Home} ${inter.className}`}>
        <div>
          <h1>H1 Title</h1>
          <h2>H2 Title</h2>
          <h3>H3 Title</h3>
          <h4>H4 Title</h4>
          <h5>H5 Title</h5>
          <h6>H6 Title</h6>
          <div>Body text</div>
        </div>

        <div className={styles.Home__col}>
          <div className={styles.Home__row}>
            <Card />
          </div>
          <div className={styles.Home__row}>
            <Card heading="h3" />
            <Card heading="h3" />
          </div>
          <div className={styles.Home__row}>
            <Card heading="h4" />
            <Card heading="h4" />
            <Card heading="h4" />
          </div>
        </div>
      </main>
    </>
  );
}
